//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prac6AvtotizaciaDB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int Id_Client { get; set; }
        public Nullable<int> Id_Role { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public string Password { get; set; }
    
        public virtual Role Role { get; set; }
    }
}
